spring.application.name=currency-converter-java

server.port=8080

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

app.apiURL=https://v6.exchangerate-api.com/v6/6017ec15ad8e55f942601fd0/latest/

spring.datasource.url=jdbc:postgresql://localhost:5432/exchange_rate_db
spring.datasource.username=postgres
spring.datasource.password=qazwsx123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
